project_name: 'linode-tagger'
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.BuildDate={{ .CommitDate }}
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
    binary: tagger
dockers:
  # build latest and specific tag version images
  - image_templates:
      - "ghcr.io/tjhop/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/tjhop/{{.ProjectName}}:latest"
    goos: linux
    goarch: amd64
    use: docker
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/tjhop/linode-tagger"
    - "--label=org.opencontainers.image.description='Tool to bulk enforce API tag sets on Linode API Objects'"
    - "--label=org.opencontainers.image.licenses=MIT"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
nfpms:
  - package_name: 'linode-tagger'
    homepage: 'https://github.com/tjhop/tagger'
    maintainer: 'TJ Hoplock <t.hoplock@gmail.com>'
    description: 'Tool to bulk enforce API tag sets on Linode API Objects'
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/tjhop/mango/README.md
      - src: ./packaging/etc/tagger.yml
        dst: /usr/share/doc/tjhop/tagger/example/tagger.yml
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
      - '^ci(?:\(\w+\))?\!?:'
      - '^docs(?:\(\w+\))?\!?:'
      - '^test(?:\(\w+\))?\!?:'
      - '^chore(?:\(\w+\))?\!?:'
      - '^style(?:\(\w+\))?\!?:'
